<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://localhost/tienda_wdsl/TiendaOnlineOO/tienda/include" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost/tienda_wdsl/TiendaOnlineOO/tienda/include">
    <wsdl:types>
        <xsd:schema targetNamespace="http://localhost/tienda_wdsl/TiendaOnlineOO/tienda/include"/>
    </wsdl:types>
    <wsdl:message name="obtienePrecioProductoRequest">
        <wsdl:part name="codigo" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="obtienePrecioProductoResponse">
        <wsdl:part name="obtienePrecioProductoReturn" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="BD_proxyPortType">
        <wsdl:operation name="obtienePrecioProducto">
            <wsdl:documentation/>
            <wsdl:input message="tns:obtienePrecioProductoRequest"/>
            <wsdl:output message="tns:obtienePrecioProductoResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BD_proxyBinding" type="tns:BD_proxyPortType">
        <soap-env:binding xmlns="http://schemas.xmlsoap.org/wsdl/soap/" style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="obtienePrecioProducto">
            <soap-env:operation xmlns="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://localhost/tienda_wdsl/TiendaOnlineOO/tienda/include/servicio.php?method=obtienePrecioProducto" style="rpc"/>
            <wsdl:input>
                <soap-env:body xmlns="http://schemas.xmlsoap.org/wsdl/soap/" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </wsdl:input>
            <wsdl:output>
                <soap-env:body xmlns="http://schemas.xmlsoap.org/wsdl/soap/" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="BD_proxy">
        <wsdl:documentation/>
        <wsdl:port name="BD_proxyPort" binding="tns:BD_proxyBinding">
            <soap-env:address location="http://localhost/tienda_wdsl/TiendaOnlineOO/tienda/include/servicio.php"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
